apiVersion: webapp.demo.my-watchlist.io/v1
kind: MyWatchlist
metadata:
  name: mywatchlist-sample
spec:
  redisName: redis-sample # points to the DB to be used
  frontend:
    containerImage: micabe/redis-watchlist
    resources:
      requests:
        cpu: 55m
